### PR TITLE
Sync upstream workflow

### PR DESCRIPTION
**Pull request by joemcgill**
This adds a new github workflow that automates syncing trunk and release branches from the upstream repo.

### CODE REVIEW

**Comment by joemcgill** [comment]
Something that occurred to me while working on this PR is that for this workflow to actually run on this repo, we would need to do one of the following:

1. Merge these changes to our trunk branch, causing this fork's `trunk` branch to deviate from the upstream `trunk`, which is not ideal.
2. Change the default branch in our repo to another branch, like `10up-trunk` or something and merge this PR into that branch instead so the automated workflows will run without effecting the mirrored `trunk` branch.
3. Add this workflow to a totally separate repo that runs this task, so long as it also has access to push changes to this repo as well.

**Comment by jeffpaul** [comment]
@joemcgill what if the sync doesn't run as a GitHub Action but rather via the older style [Probot app](https://probot.github.io/) integration?

**Comment by jeffpaul** [comment]
...^ I believe would just be an app integration to this repo and not an actual code differentiation in the `trunk` branch AND allow us to not have a tad wonky `10up-trunk` branch that causes additional branch workflow oddities (perhaps)?

**Comment by joemcgill** [comment]
@jeffpaul I think a separate bot integration would work fine for my specific use case here, but not for testing out new workflows that are meant to run on pushes to `trunk`, like the one being developed in #16, which is what this PR is in support of.

**Comment by felixarntz** [comment]
@jeffpaul I'm personally not familiar with how that works, but that sounds like a great alternative to me, as it would avoid the need to have extra code in `trunk` or change the default branch, which comes with its own workflow concerns.

@joemcgill Additionally to syncing `trunk`, we probably need to also consider afterwards merging the fork's `trunk` back into the `feature/automated-performance-testing-mvp` branch, to ensure that branch's performance measurement workflow picks up the updates regularly (which I think is the main reason we are trying to automate regular updates from upstream `trunk` in the first place).

**Comment by jeffpaul** [comment]
@joemcgill forgive my ignorance on the broader goal for #16, but a quick review there seems like perhaps that could be a PR directly to 'wordpress/wordpress-develop' and have it run as a first party core action?

**Comment by joemcgill** [comment]
I spent a bit more time looking into this, and it does look like there is a Probot app at https://github.com/wei/pull that can keep the `trunk` branch of this repo in sync with any upstream changes to the `trunk` branch of the `WordPress/wordpress-develop`. It supports some advanced configuration that we could use to sync changes to a feature branch, but that would also require that we add a config file to our default branch, which takes us back to the original dilemma we're trying to work around, in which we don't modify `trunk` in this fork.

So, I'm still feeling a bit stuck with how to automatically run a workflow on every commit when that workflow doesn't exist in the repo's default branch. My end goal here is to be able to run the workflow we're developing in the [feature/automated-performance-testing-mvp](https://github.com/10up/wordpress-develop/tree/feature/automated-performance-testing-mvp) branch automatically when new code is added upstream (after we sync it to our fork) _before_ this feature is merged into core, so we can begin collecting metrics without waiting for this to be added to core.

It seems our options are basically:

1. Use a separate service to automate pushing changes from trunk to our feature branch in order to trigger workflow events
2. Temporarily change the default branch of this repo to a different branch where we can include a scheduled workflow to handle syncing commits from the upstream repo to our feature branch
3. Manually trigger these events whenever we want to test the process, and not worry about getting metrics for each commit until this is included in core

I'm happy to start with option 3 for now, assuming we're able to get this new workflow merged to core fairly quickly, but will want to consider a secondary option if we need to let this workflow run in our fork for a while.

**Comment by joemcgill** [comment]
This no longer seems applicable, so going to close it and we can revisit if needed later.

**Pull request closed without merging**
