### PR TITLE
Core PR Iteration - Add Test Coverage Indicators & Failure Messages for Enhancing The WP Scripts API With a Loading Strategy

### PR DESCRIPTION
**Pull request by 10upsimon**
Addresses PR feedback in https://github.com/WordPress/wordpress-develop/pull/4391 regarding adding `@covers` to test function doc blocks.

### CODE REVIEW

**Comment by 10upsimon** [comment]
@joemcgill @westonruter any chance you can lay eyes on this this week please? Specifically inviting opinions around use of `@covers` and whether we feel it's alright as proposed in this PR, or too verbose. 

Thank you both!

**Comment by westonruter** [comment]
@spacedmonkey since you originally called out the missing `@covers` tags (https://github.com/WordPress/wordpress-develop/pull/4391#discussion_r1180453437), does this resolve your PR feedback?

**Comment by 10upsimon** [comment]
Noting that with some recent discussions in some auxiliary PR's (such as https://github.com/10up/wordpress-develop/pull/64) some test syntax might be changed to remove reference to `get_normalized_script_args`.

**Review by spacedmonkey — APPROVED** [review]
LGTM

**Comment by 10upsimon** [comment]
Thanks @spacedmonkey . @joemcgill @kt-12 I'm holding off on progressing this until we have a merge on https://github.com/10up/wordpress-develop/pull/64 as I believe we need to remove the `get_normalized_script_args()` test(s) and references to it in a few `@covers` doc block items.

Once that is merged (I'm keeping an eye on that) I'll make the necessary changes herein and we can proceed to get this into the base PR.

**Comment by westonruter** [comment]
> Once that is merged (I'm keeping an eye on that) I'll make the necessary changes herein and we can proceed to get this into the base PR.

It's merged!

**Comment by 10upsimon** [comment]
I've had to resolve a couple of conflicts on this branch following recent merges into the base PR. I will be merging this branch now, and conducting tests on the base PR to ensure that all is still good there.

**Pull request merged**
